# Generated by Django 5.1.5 on 2026-03-10 00:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SEARCHING', max_length=20)),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=10)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, default=Decimal('0.35'), max_digits=10)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
    ]
