# Generated by Django 5.1.5 on 2026-03-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_pickup_latitude_trip_pickup_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_polyline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='routing_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
