# Generated by Django 5.1.5 on 2026-03-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_cnh_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_cpf_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_selfie_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_verification_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
